---
- name: Install Filebeat
  yum:
    name: filebeat
    state: present
  tags: sof-elk_filebeat

- name: Configure filebeat
  file:
    src: '/usr/local/sof-elk/lib/configfiles/filebeat.yml'
    dest: '/etc/filebeat/filebeat.yml'
    state: link
    force: yes
  notify: restart filebeat
  tags: sof-elk_filebeat

- name: Create filebeat input directories
  file:
    dest: '/logstash/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 01777
  with_items:
    - nfarch
    - zeek
    - httpd
    - passivedns
    - syslog
    - kape
  notify: restart filebeat
  tags: sof-elk_filebeat

- name: Start and enable Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started
  tags: sof-elk_filebeat
