---
# This playbook configures a single-instance SOF-ELK(R) system

- name: Run all preload steps required for a SOF-ELK system
  hosts: all
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: "Get current git branch"
      command: "git rev-parse --abbrev-ref HEAD"
      args:
        chdir: "{{ playbook_dir }}"
      register: git_branch_result
      check_mode: no
      delegate_to: 127.0.0.1
    - set_fact:
        git_branch: "{{ git_branch_result.stdout }}"

  vars_prompt:
    - name: disable_root
      prompt: "Disable root account from native login (default: yes)?"
      default: yes
      private: no
    - name: geoip_accountid
      prompt: "Enter GeoIP Account ID"
      private: no
    - name: geoip_licensekey
      prompt:  "Enter GeoIP License Key"
      private: no
    - name: geoip_config_persist
      prompt: "Do you want GeoIP account/license data to persist after installation (default: no)?"
      default: no
      private: no

  roles:
    - sof-elk_base
    - elasticsearch
    - cerebro
    - logstash
    - filebeat
    - kibana
    - elastalert
    - domain_stats
    - freq

    - sof-elk_finalize
